[RelEng] Add JavaDoc-Basher Pull-Request check
The added check runs the javadoc-basher on each PR and ensures the
JavaDoc of all public API elements is synchronized for all platforms.
In case that run leads to changes in the git worktree, the check fails.

diff --git a/.github/workflows/pr-checks.yml b/.github/workflows/pr-checks.yml
--- a/.github/workflows/pr-checks.yml
+++ b/.github/workflows/pr-checks.yml
@@ -19,3 +19,23 @@ jobs:
     with:
       botName: Eclipse Platform Bot
       botMail: platform-bot@eclipse.org
+
+  check-javadoc-consistency:
+    runs-on: ubuntu-latest
+    steps:
+    - uses: actions/checkout@ff7abcd0c3c05ccf6adc123a8cd1fd4fb30fb493 # v5.0.0
+    - uses: actions/setup-java@de5a937a1dc73fbc1a67d7d1aa4bebc1082f3190 # v5.0.0
+      with:
+        java-version: 25
+        distribution: 'temurin'
+        cache: maven
+    - name: Run JavaDoc basher
+      run: >
+        mvn --non-recursive --batch-mode --no-transfer-progress
+        -Pjavadoc-basher exec:exec@run-javadoc-basher
+    - name: Verify no changes
+      run: |
+        if ! git diff --exit-code ; then
+          echo "::error title=Inconsistent JavaDoc::JavaDoc-Basher discovered JavaDoc inconsistencies between implementations, which must be resolved."
+          exit 1
+        fi
